### ISSUE TITLE
Update suggestions for the library to be used by another project via the Zig package manager

### ISSUE THREAD

**Issue by FObersteiner** [ZigEmbeddedGroup/serial#18]
Hi there! I needed a simple serial reader application today and was very happy to find your library. I noted that some features are missing for the library to be used by other projects via the Zig package manager. For now, I have forked the repo and made some changes there. That works fine for me. If you're interested, here's a couple of suggestions:
- add a `zon` file (required)
- set a git tag (not required but convenient, for referencing the lib in the client's `zon` file)
- use `std.fs.max_path_bytes` instead of `std.fs.MAX_PATH_BYTES` (Zig 0.14-dev requirement; the lower-case variant also works with Zig 0.12 and 0.13 stable)

Those are probably maintenance updates, but if you'd like, I can also make a PR.

**Comment by ikskuh** [comment]
Always happy to receive PRs for such chores :)

**Comment by FObersteiner** [comment]
btw. after adding the test step, I noted that the tests only work if you actually have a serial port available ^^ I didn't notice this on my other machine where I happen to have a USB-to-Serial device attached, and the tests passed.
