### ISSUE TITLE
Baud rate not set correctly on Linux

### ISSUE THREAD

**Issue by FObersteiner** [ZigEmbeddedGroup/serial#24]
I noticed that on Linux, the baud rate specified in `configureSerialPort` is ignored. Some default rate is used, for example on my Debian system that is 9.6k.

If I read the code correctly, the baud rate is not set to the cflag of the settings (termios). Relevant source code starts [here](https://github.com/ZigEmbeddedGroup/serial/blob/c5704c25eb0dc59cc15fc049a0bfb2ce978c757e/src/serial.zig#L698). To fix this, I have the following code in [my fork](https://github.com/FObersteiner/serial/blob/5507b073ea6f8e09976b60430d40b194a7540950/src/serial.zig#L697):

```zig
// [baudmask is obtained before...]

// initialize CFLAG with the baudrate bits
var strct_cflag: std.os.linux.tc_cflag_t = @bitCast(@intFromEnum(baudmask));
strct_cflag.CREAD = true; // 0x80

// [...]
settings.cflag = strct_cflag;

// [...]
```
This works fine for me. I can make a PR if you like. However, since this code also runs for Mac, note that I cannot test this on a Mac since I don't have access to one.

**Comment by ikskuh** [comment]
Yes, please make a PR :)

**Comment by FObersteiner** [comment]
> Yes, please make a PR :)

alright, here you go, #25 

I also noted that the main source code file `serial.zig` is relatively long (1k+ loc) by now, I'd probably move platform-specific code to individual zig files. Is that something you'd appreciate? I mean, it's more of a cosmetic thing since decent code editor allows to jump around and find things pretty quickly independent of file structure. Still, it might help readability, so I could give it some more thought.

**Comment by ikskuh** [comment]
> I also noted that the main source code file serial.zig is relatively long (1k+ loc) by now, I'd probably move platform-specific code to individual zig files. Is that something you'd appreciate? I

Not before 10kloc or something. 1kloc is still way easier to manage in a single file instead of splitting stuff into multiple of files making everything harder, including readability (ctrl-f doesn't work across file boundaries for example)

**Comment by FObersteiner** [comment]
Alright then, let's see how large this thing grows then :)
